./compileJS -O engine2d.min.js\
 engine/ENGINE2D.js\
 engine/Vector2.js\
 engine/Matrix3.js\
 engine/Vector.js\
 engine/Set.js\
 engine/Promise.js\
 engine/Promise.js\
 engine/LogManager.js\
 engine/LoadingManager.js\
 engine/Cache.js\
 engine/Loader.js\
 engine/Simulator.js\
 engine/Renderer.js\
 engine/AudioRenderer.js\
 engine/Interval.js\
 engine/Message.js\
 engine/MessageQueue.js\
 engine/Game.js\
 engine/GameState.js\
 engine/Audio.js\
 engine/Material.js\
 engine/Geometry.js\
 engine/TransitionFunction.js\
 engine/ConditionFunction.js\
 engine/EvolutionFunction.js\
 engine/Object2D.js\
 engine/Empty.js\
 engine/AudioObject.js\
 engine/Camera.js\
 engine/Boundary.js\
 engine/Trigger.js\
 engine/StaticObject.js\
 engine/DynamicObject.js\
 engine/InteractingObject.js\
 engine/Scene.js\
 engine/InputState.js\
 engine/Control.js